#!/bin/bash
echo stopping watchers...
docker stop watchers
echo removing watchers...
docker rm watchers
echo removing watchers_aws image....
docker image rm watchers_aws
echo loading watchers_aws image....
docker load -i docker_images/watchers_aws.tar
echo running watchers contaner...
docker run -d -p 8010:8000 --name watchers watchers_aws
echo done....
